# Generated by Django 3.0.7 on 2020-08-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countystat',
            name='percentage_of_cases',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='transmissonstats',
            name='close_contact',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='transmissonstats',
            name='community_transmission',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='transmissonstats',
            name='travel_abroad',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
