# Generated by Django 3.0.7 on 2020-08-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtracker', '0003_auto_20200801_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='covidhistory',
            options={'verbose_name': 'Covid History', 'verbose_name_plural': 'Covid History'},
        ),
        migrations.AddField(
            model_name='agebarchartstats',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='countystat',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='covidhistory',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='covidstats',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='genderstats',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hospitalbarchartstats',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transmissonstats',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
