# Generated by Django 3.0.7 on 2020-08-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtracker', '0004_auto_20200801_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agebarchartstats',
            options={'verbose_name': 'Age Data', 'verbose_name_plural': 'Age Data'},
        ),
        migrations.AlterModelOptions(
            name='countystat',
            options={'verbose_name': 'County', 'verbose_name_plural': 'County'},
        ),
        migrations.AlterModelOptions(
            name='covidstats',
            options={'verbose_name': 'Covid Data', 'verbose_name_plural': 'Covid Data'},
        ),
        migrations.AlterModelOptions(
            name='dailydata',
            options={'verbose_name': 'Daily Data', 'verbose_name_plural': 'Daily Data'},
        ),
        migrations.AlterModelOptions(
            name='genderstats',
            options={'verbose_name': 'Gender Data', 'verbose_name_plural': 'Gender Data'},
        ),
        migrations.AlterModelOptions(
            name='hospitalbarchartstats',
            options={'verbose_name': 'Hospital Data', 'verbose_name_plural': 'Hospital Data'},
        ),
        migrations.AlterModelOptions(
            name='transmissonstats',
            options={'verbose_name': 'Transmission Data', 'verbose_name_plural': 'Transmission Data'},
        ),
        migrations.AlterField(
            model_name='agebarchartstats',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='countystat',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='covidhistory',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='covidstats',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='genderstats',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hospitalbarchartstats',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transmissonstats',
            name='date',
            field=models.DateField(),
        ),
    ]
