# Generated by Django 3.0.7 on 2020-08-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidtracker', '0006_covidstats_hospitalised'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countystat',
            name='change_since_yesterday',
        ),
    ]
