# Generated by Django 3.0.7 on 2020-08-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtracker', '0007_remove_countystat_change_since_yesterday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidstats',
            name='date',
            field=models.DateField(unique_for_date=True),
        ),
    ]
