# Generated by Django 3.0.7 on 2020-08-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtracker', '0008_auto_20200806_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidstats',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='covidstats',
            unique_together={('date', 'deaths_today', 'diagnosed_today', 'hospitalised', 'total_diagnosed', 'total_death', 'healthcare_workers_diagnosed', 'total_clusters', 'cluster_diagnosed', 'icu', 'median_age')},
        ),
    ]
