# Generated by Django 3.0.7 on 2020-08-07 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidtracker', '0009_auto_20200806_2307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyData',
        ),
        migrations.AlterField(
            model_name='covidhistory',
            name='age_data',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='covidtracker.AgeBarChartStats'),
        ),
        migrations.AlterField(
            model_name='covidhistory',
            name='covid_stats',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='covidtracker.CovidStats'),
        ),
        migrations.AlterField(
            model_name='covidhistory',
            name='gender_data',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='covidtracker.GenderStats'),
        ),
        migrations.AlterField(
            model_name='covidhistory',
            name='hospital_data',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='covidtracker.HospitalBarChartStats'),
        ),
        migrations.AlterField(
            model_name='covidhistory',
            name='transmission_data',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='covidtracker.TransmissonStats'),
        ),
    ]
