# Generated by Django 3.0.7 on 2020-09-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidtracker', '0010_auto_20200807_0305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransmissonStats',
            new_name='TransmissionStats',
        ),
    ]
